# Generated by Django 4.0.6 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
