# Generated by Django 4.0.6 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_artist_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_no',
            field=models.IntegerField(default=0),
        ),
    ]
