# Generated by Django 4.0.6 on 2024-03-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_song_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_no',
        ),
    ]
