# Generated by Django 4.0.6 on 2024-03-12 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
