# Generated by Django 4.0.6 on 2024-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0004_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_modified',
            field=models.CharField(default='2024-20-13 21:20', max_length=200),
        ),
    ]
